<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
	  <Compile Include="obj\Debug\net8.0\BarberiaWeb.AssemblyInfo.cs" />
	  <Compile Include="obj\Debug\net8.0\BarberiaWeb.GlobalUsings.g.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="obj\BarberiaWeb.csproj.nuget.dgspec.json" />
	  <Content Include="obj\Debug\net8.0\BarberiaWeb.csproj.FileListAbsolute.txt" />
	  <Content Include="obj\Debug\net8.0\rpswa.dswa.cache.json" />
	  <Content Include="obj\Debug\net8.0\staticwebassets.references.upToDateCheck.txt" />
	  <Content Include="obj\Debug\net8.0\staticwebassets.removed.txt" />
	  <Content Include="obj\project.assets.json" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Templates\**\*.html">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="bin\Debug\net8.0\cs\" />
	  <Folder Include="bin\Debug\net8.0\de\" />
	  <Folder Include="bin\Debug\net8.0\es\" />
	  <Folder Include="bin\Debug\net8.0\fr\" />
	  <Folder Include="bin\Debug\net8.0\it\" />
	  <Folder Include="bin\Debug\net8.0\ja\" />
	  <Folder Include="bin\Debug\net8.0\ko\" />
	  <Folder Include="bin\Debug\net8.0\pl\" />
	  <Folder Include="bin\Debug\net8.0\pt-BR\" />
	  <Folder Include="bin\Debug\net8.0\runtimes\unix\lib\net6.0\" />
	  <Folder Include="bin\Debug\net8.0\runtimes\win-arm64\native\" />
	  <Folder Include="bin\Debug\net8.0\runtimes\win-arm\native\" />
	  <Folder Include="bin\Debug\net8.0\runtimes\win-x64\native\" />
	  <Folder Include="bin\Debug\net8.0\runtimes\win-x86\native\" />
	  <Folder Include="bin\Debug\net8.0\runtimes\win\lib\net6.0\" />
	  <Folder Include="bin\Debug\net8.0\ru\" />
	  <Folder Include="bin\Debug\net8.0\tr\" />
	  <Folder Include="bin\Debug\net8.0\zh-Hans\" />
	  <Folder Include="bin\Debug\net8.0\zh-Hant\" />
	  <Folder Include="obj\Debug\net8.0\refint\" />
	  <Folder Include="obj\Debug\net8.0\ref\" />
	  <Folder Include="obj\Debug\net8.0\staticwebassets\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="obj\BarberiaWeb.csproj.nuget.g.props" />
	  <None Include="obj\BarberiaWeb.csproj.nuget.g.targets" />
	  <None Include="obj\Debug\net8.0\apphost.exe" />
	  <None Include="obj\Debug\net8.0\BarberiaWeb.AssemblyInfoInputs.cache" />
	  <None Include="obj\Debug\net8.0\BarberiaWeb.assets.cache" />
	  <None Include="obj\Debug\net8.0\BarberiaWeb.csproj.AssemblyReference.cache" />
	  <None Include="obj\Debug\net8.0\BarberiaWeb.GeneratedMSBuildEditorConfig.editorconfig" />
	  <None Include="obj\project.nuget.cache" />
	</ItemGroup>

</Project>