// <auto-generated />
using System;
using BarberiaWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberiaWeb.Migrations
{
    [DbContext(typeof(BarberiaDbContext))]
    [Migration("20260822181656_AgregarGaleriaAOrdenSecciones")]
    partial class AgregarGaleriaAOrdenSecciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarberiaWeb.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("NegocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NegocioId");

                    b.HasIndex("Telefono");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BarberiaWeb.Models.Negocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorAcento")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ColorFondo")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ColorFondoClaro")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ColorPrimario")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ColorTexto")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ColorTextoClaro")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("DescripcionNosotros")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeroImagenUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MapaEmbedUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrdenSeccionesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rubro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ThemePresetId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Negocios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorAcento = "#d4af37",
                            ColorFondo = "#ffffff",
                            ColorFondoClaro = "#f8f8f8",
                            ColorPrimario = "#1a1a1a",
                            ColorTexto = "#333333",
                            ColorTextoClaro = "#666666",
                            DescripcionNosotros = "En LUCK BARBER, creemos que cada corte es una obra de arte. Desde 2018, nos dedicamos a ofrecer más que un servicio de barbería: creamos experiencias únicas donde el estilo y la personalidad de cada cliente se encuentran.\n\nNuestro equipo de barberos profesionales está capacitado en las últimas tendencias y técnicas clásicas, garantizando resultados impecables en cada visita. Utilizamos productos premium y trabajamos con atención al detalle para que salgas luciendo exactamente como lo imaginás.\n\nUbicados en el corazón de Rosario, nos hemos convertido en el punto de encuentro para quienes buscan calidad, confianza y un ambiente relajado. Ya sea un corte clásico, un fade moderno o un arreglo de barba profesional, en LUCK BARBER encontrás tu mejor versión.",
                            Direccion = "Av. Pellegrini 1234, Rosario, Santa Fe",
                            Email = "luckbarber@gmail.com",
                            FechaActualizacion = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "LUCK BARBER",
                            OrdenSeccionesJson = "[\"servicios\",\"nosotros\",\"galeria\",\"contacto\"]",
                            Rubro = "Barberia",
                            Telefono = "+54 341 690-1109",
                            WhatsApp = "5493416901109"
                        });
                });

            modelBuilder.Entity("BarberiaWeb.Models.NegocioGaleriaImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("NegocioGaleriaImagenes");
                });

            modelBuilder.Entity("BarberiaWeb.Models.NegocioHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abierto")
                        .HasColumnType("bit");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<string>("HoraApertura")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoraCierre")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("NegocioHorarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abierto = true,
                            DiaSemana = 1,
                            HoraApertura = "09:00",
                            HoraCierre = "20:00",
                            NegocioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Abierto = true,
                            DiaSemana = 2,
                            HoraApertura = "09:00",
                            HoraCierre = "20:00",
                            NegocioId = 1
                        },
                        new
                        {
                            Id = 3,
                            Abierto = true,
                            DiaSemana = 3,
                            HoraApertura = "09:00",
                            HoraCierre = "20:00",
                            NegocioId = 1
                        },
                        new
                        {
                            Id = 4,
                            Abierto = true,
                            DiaSemana = 4,
                            HoraApertura = "09:00",
                            HoraCierre = "20:00",
                            NegocioId = 1
                        },
                        new
                        {
                            Id = 5,
                            Abierto = true,
                            DiaSemana = 5,
                            HoraApertura = "09:00",
                            HoraCierre = "20:00",
                            NegocioId = 1
                        },
                        new
                        {
                            Id = 6,
                            Abierto = true,
                            DiaSemana = 6,
                            HoraApertura = "09:00",
                            HoraCierre = "18:00",
                            NegocioId = 1
                        },
                        new
                        {
                            Id = 7,
                            Abierto = false,
                            DiaSemana = 0,
                            NegocioId = 1
                        });
                });

            modelBuilder.Entity("BarberiaWeb.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int>("NegocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Corte profesional",
                            DuracionMinutos = 30,
                            NegocioId = 1,
                            Nombre = "Corte Clásico",
                            Precio = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Combo completo",
                            DuracionMinutos = 45,
                            NegocioId = 1,
                            Nombre = "Corte + Barba",
                            Precio = 7500m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Perfilado de barba",
                            DuracionMinutos = 20,
                            NegocioId = 1,
                            Nombre = "Barba",
                            Precio = 3500m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Corte para niños",
                            DuracionMinutos = 25,
                            NegocioId = 1,
                            Nombre = "Corte Niños",
                            Precio = 4000m
                        });
                });

            modelBuilder.Entity("BarberiaWeb.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTurno")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoraTurno")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NegocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaTurno");

                    b.HasIndex("NegocioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("BarberiaWeb.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BarberiaWeb.Models.Cliente", b =>
                {
                    b.HasOne("BarberiaWeb.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("BarberiaWeb.Models.NegocioGaleriaImagen", b =>
                {
                    b.HasOne("BarberiaWeb.Models.Negocio", "Negocio")
                        .WithMany("Galeria")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("BarberiaWeb.Models.NegocioHorario", b =>
                {
                    b.HasOne("BarberiaWeb.Models.Negocio", "Negocio")
                        .WithMany("Horarios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("BarberiaWeb.Models.Servicio", b =>
                {
                    b.HasOne("BarberiaWeb.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("BarberiaWeb.Models.Turno", b =>
                {
                    b.HasOne("BarberiaWeb.Models.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberiaWeb.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberiaWeb.Models.Servicio", "Servicio")
                        .WithMany("Turnos")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Negocio");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("BarberiaWeb.Models.Usuario", b =>
                {
                    b.HasOne("BarberiaWeb.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("BarberiaWeb.Models.Cliente", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("BarberiaWeb.Models.Negocio", b =>
                {
                    b.Navigation("Galeria");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("BarberiaWeb.Models.Servicio", b =>
                {
                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
